title:              Sentaan Reviews
email:              sentaanyt@gmail.com
description:        A site where I review and talk about random things I feel like
author:             Sentaan
baseurl:            
url:                

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  sentaan.talks
tiktok_username: sentaan.reviews
linkedin_username:
lastfm_username: sentaan
serialized_username: sentaan
goodreads_username: sentaan
storygraph_username: sentaan
youtube_username: sentaan

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
